---
title: "Bike_Share"
format: pdf
editor: visual
---

## Set up

```{r}
#| output: false
#| message: false
library(tidyverse)
library(tidymodels)
library(vroom)
library(ggplot2)
library(dplyr)
library(patchwork)
library(glmnet)
library(rpart)
library(bonsai)
library(lightgbm)

```

## Import

```{r}
#| output: false
#| message: false

train<- vroom("C:/Users/rileyw02/Downloads/train.csv")
test <- vroom("C:/Users/rileyw02/Downloads/test.csv")
```

## Clean

```{r}
train <- train |>
  select(-casual, -registered)|>
  mutate(count = log(count))
```

## Model Making

```{r}
#Tree Model
model <- bart(trees=tune()) |> # BART figures out depth and learn_rate9
set_engine("dbarts") |> # might need to install10
set_mode("regression")

```

## Recipe

```{r}
bike_recipe <- recipe(count~., data=train) |>
  step_mutate(weather = ifelse(weather == 4, 3, weather),
              weekend = ifelse(wday(datetime) %in% c(1,7),1,0),
              rush_hour = ifelse(hour(datetime) %in% c(7:9,16:19),1,0)) |> 
  step_date(datetime, features=c("dow", "month", "year", "doy")) |>
  step_time(datetime, features= "hour") |>
  step_rm(datetime)|>
  step_interact(terms= ~ temp:humidity + temp:windspeed +season:humidity) |>
  step_poly(temp, humidity, degree = 2) |>
  step_dummy(all_nominal_predictors()) |>
  step_normalize(all_numeric_predictors())
  
  # step_mutate(weather = factor(weather)) %>%
  # step_date(datetime, features=c("dow", "month", "year", "doy")) %>% # Add more date features
  # step_time(datetime, features=c("hour", "minute")) %>%
  # step_mutate(
  #   hour = as.numeric(format(datetime, "%H")),
  #   month = as.numeric(format(datetime, "%m")),
  #   year = as.numeric(format(datetime, "%Y")),
  #   weekend = ifelse(datetime_dow %in% c("Sat", "Sun"), 1, 0),
  #   rush_hour = ifelse(hour %in% c(7,8,9,17,18,19), 1, 0)
  # ) %>%
  # step_interact(terms = ~ hour:season + hour:workingday + hour:holiday) %>% # Add interactions
  # step_dummy(all_nominal_predictors()) %>%
  # step_rm(datetime) %>% 
  # step_zv(all_predictors()) |>
  # step_lincomb(all_predictors()) |>
  # step_normalize(all_numeric_predictors()) |>
  # step_poly(temp, atemp, humidity, degree=2) # Add polynomial features
prepped_recipe <- prep(bike_recipe)
```

## Baking (Optional if you are using a workflow)

```{r}
train_processed <- bake(prepped_recipe, new_data = train)
test_processed  <- bake(prepped_recipe, new_data = test) 
```

## Workflow

```{r}
wf <- workflow() |>
add_recipe(bike_recipe) |>
add_model(model)
```

## Tuning

```{r}
## Grid of values to tune over13
tune_grid <- grid_regular(
  trees(),
  levels = 5   # or however many points you want
)

## Split data for CV
folds <- vfold_cv(train, v = 2)

## Run the CV
param_tune <- tune_grid(
  wf,
  resamples = folds,
  grid = tune_grid,
  metrics = metric_set(rmse, rsq))

## Plot Results (example)
collect_metrics(param_tune) |> # Gathers metrics into DF
filter(.metric=="rmse") |>
ggplot(aes(x = trees, y = mean)) +
geom_line() +
geom_point() +
labs(x = "Number of Trees",
y = "RMSE")

## Find Best Tuning Parameters
best_param <- select_best(param_tune, metric="rmse")

## Finalize the Workflow & fit it
final_wf <- wf |>
finalize_workflow(best_param) |>
fit(data=train)

```

## Predictions

```{r}
## Predict
#final_wf |>
#predict(new_data = test)

test_preds <- predict(final_wf, new_data = test)
test_preds <- test_preds |>
  mutate(.pred = exp(.pred))
```

## Kaggle Submission

```{r}

kaggle_submission <- test_preds |>
  bind_cols(test) |> 
  select(datetime, .pred) |>
  rename(count = .pred) |>  
  mutate(count = pmax(0, count)) |> 
  mutate(datetime = as.character(format(datetime)))

## Write out the file9
vroom_write(x = kaggle_submission, 
            file = "~/GitHub/Stat 348/Bike-Share/Kaggle_Submission.csv", 
            delim = ",")
```
